### ISSUE TITLE
Connection State UI - can't make it work

### ISSUE THREAD

**Issue by vd3d** [Blazorade/Blazorade-Core#7] opened 2020-07-20 18:20 UTC
Hi,

Your "Connection State UI" component is a great idea, but I can't make it work. I still have the same default message "cannot reconnect" :-(

I have follow this:
https://mikaberglund.com/2020/04/13/customizing-connection-state-ui-in-blazor-server-applications-with-blazorade/

The component is in the App.razor and I have copy/paste your code...

I use the very last version of .NET, maybe it is related... or not, any idea ?

PS: My way of simulating it, is to put the computer in "sleep mode" or to put a long break point on the "server" code to have a timeout. If you have better idea, it is welcome too :-)

Thx

**Comment by MikaBerglund** [comment] 2021-01-18 12:25
Hi!

I am sooooo sorry for missing this issue completely. Seems that I don't get any e-mail alerts when there are new issues filed. I'll have to look into that.

Have you tried the [ServerApp](https://github.com/Blazorade/Blazorade-Core/tree/master/ServerApp) that ships with the source code for Blazorade Core? In the [App](https://github.com/Blazorade/Blazorade-Core/blob/master/ServerApp/App.razor) component there is the default version of the ComponentReconnectModal component without any custom templates defined. I just tried it, and it works.

Probably the easiest way to simulate a "server loss" is to start your application in Visual Studio without debugging (Ctrl+F5), and then just shutting down the site in IIS Express. When you debug with IIS Express, you get a IIS Express icon in the system tray, where you can then shut it down. This should bring up the custom dialog.

Note that this only works with Blazor Server.

Again, I am truly sorry for this half a year delay ;(

**Comment by MikaBerglund** [comment] 2021-02-07 11:40
As I cannot reproduce this problem, I will close it for now. However, if you still have the problem, please feel free to comment on this issue, and we'll reopen it.

**Closed as completed by MikaBerglund** 2021-02-07 11:40 UTC
